### PR TITLE
so we can find the real error

### PR DESCRIPTION
**Pull request by dmarcuse**

### CODE REVIEW

**Comment by brendanashworth** [comment]
What importance does this really provide though? The previous was simply a shorthand for your new one.

**Comment by dmarcuse** [comment]
Good point. I don't actually know...

**Comment by cloyd1815** [comment]
None

**Comment by cloyd1815** [comment]
The only difference is if he had added an else statement

**Comment by brendanashworth** [comment]
Yeah, there is no real functionality change here.

**Pull request closed without merging**
